"""Loader for hand-committed AI commentary data.

Commentary lives in content/commentary/{event_id}.json, generated by Claude
Code on a developer machine and committed to the repository. The build reads
it here and renders it to HTML. Absence of a file is the normal case for
events that have not been processed yet, not an error.
"""
import json
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Optional

from ..config import COMMENTARY_PATH

# Bumped when the on-disk format changes in a way the renderer must know about
SCHEMA_VERSION = 1

# Content sections in render order, mapped to their page headings. This is the
# single source of both the order and the labels: the generator builds the table
# of contents from it and the template reads the heading from the same entry.
SECTION_LABELS = {
    'summary': 'あらすじ',
    'revealed_facts': '判明した事実',
    'open_threads': '伏線・未回収の謎',
    'glossary': '用語集',
}


@dataclass
class SummarySection:
    """One chronological block of the plot summary."""
    heading: str
    body: str
    stage_refs: List[str] = field(default_factory=list)


@dataclass
class RevealedFact:
    """A fact established by this event's story."""
    fact: str
    basis: str  # 'stated' or 'implied'
    stage_refs: List[str] = field(default_factory=list)

    @property
    def basis_label(self) -> str:
        """Japanese label for the basis of the fact."""
        return {'stated': '明言', 'implied': '示唆'}.get(self.basis, self.basis)


@dataclass
class OpenThread:
    """An unresolved question or piece of foreshadowing."""
    thread: str
    context: str = ''
    stage_refs: List[str] = field(default_factory=list)


@dataclass
class GlossaryEntry:
    """A term, concept, or organization appearing in the event."""
    term: str
    definition: str
    reading: str = ''
    stage_refs: List[str] = field(default_factory=list)


@dataclass
class Commentary:
    """AI-generated commentary for a single event."""
    event_id: str
    event_name: str = ''
    schema_version: int = SCHEMA_VERSION
    generated_at: str = ''
    generator: str = ''
    summary: List[SummarySection] = field(default_factory=list)
    revealed_facts: List[RevealedFact] = field(default_factory=list)
    open_threads: List[OpenThread] = field(default_factory=list)
    glossary: List[GlossaryEntry] = field(default_factory=list)

    @property
    def is_empty(self) -> bool:
        """Whether the commentary has no content worth rendering."""
        return not (self.summary or self.revealed_facts
                    or self.open_threads or self.glossary)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Commentary':
        """Create Commentary from parsed JSON.

        Unknown keys are ignored and missing sections default to empty so a
        partially filled file still renders.
        """
        return cls(
            event_id=data.get('event_id', ''),
            event_name=data.get('event_name', ''),
            schema_version=data.get('schema_version', SCHEMA_VERSION),
            generated_at=data.get('generated_at', ''),
            generator=data.get('generator', ''),
            summary=[
                SummarySection(
                    heading=item.get('heading', ''),
                    body=item.get('body', ''),
                    stage_refs=list(item.get('stage_refs') or []),
                )
                for item in data.get('summary') or []
            ],
            revealed_facts=[
                RevealedFact(
                    fact=item.get('fact', ''),
                    basis=item.get('basis', 'stated'),
                    stage_refs=list(item.get('stage_refs') or []),
                )
                for item in data.get('revealed_facts') or []
            ],
            open_threads=[
                OpenThread(
                    thread=item.get('thread', ''),
                    context=item.get('context', ''),
                    stage_refs=list(item.get('stage_refs') or []),
                )
                for item in data.get('open_threads') or []
            ],
            glossary=[
                GlossaryEntry(
                    term=item.get('term', ''),
                    definition=item.get('definition', ''),
                    reading=item.get('reading', ''),
                    stage_refs=list(item.get('stage_refs') or []),
                )
                for item in data.get('glossary') or []
            ],
        )


@lru_cache(maxsize=None)
def load_commentary(event_id: str,
                    base_path: Path = COMMENTARY_PATH) -> Optional[Commentary]:
    """Load commentary for an event, if it exists.

    Results are cached because a build reads each event's commentary more than
    once: the event page needs to know whether to show the link, and the
    commentary page needs the content itself.

    Args:
        event_id: Event ID
        base_path: Directory holding commentary JSON files

    Returns:
        Commentary object, or None if no file exists or it cannot be parsed
    """
    path = base_path / f"{event_id}.json"
    if not path.exists():
        return None

    try:
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        # A malformed file should not break the build; validation reports it.
        print(f"Warning: could not read commentary for {event_id}: {e}")
        return None

    commentary = Commentary.from_dict(data)
    if commentary.is_empty:
        return None
    return commentary


def list_commentary_event_ids(base_path: Path = COMMENTARY_PATH) -> List[str]:
    """List event IDs that have a commentary file.

    Args:
        base_path: Directory holding commentary JSON files

    Returns:
        Sorted list of event IDs
    """
    if not base_path.exists():
        return []
    return sorted(p.stem for p in base_path.glob('*.json'))
